# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Xhq5pasSsNjLUmzhfJ50K2i2lwMluGl
"""

import pandas as pd
from google.colab import files

# Subir el archivo desde el equipo local
uploaded = files.upload()

# Obtener el nombre del archivo subido
nombre_archivo = list(uploaded.keys())[0]

# Leer el archivo CSV usando pandas
datos_avocado = pd.read_csv(nombre_archivo)

# Mostrar las primeras filas del DataFrame para verificar que se ha leído correctamente
datos_leidos = datos_avocado.head(10)

# Asignar la estructura leída a una nueva variable para uso posterior
matriz_avocados = datos_leidos

# Mostrar la estructura almacenada
matriz_avocados

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

# Primero, sube los archivos a Colab
print("Por favor, sube los archivos CSV cuando se te solicite:")
uploaded = files.upload()

# Ahora podemos cargar los archivos
# Cargar los datos de Messi
messi_comp = pd.read_csv('messi_competition_goals.csv')
messi_year = pd.read_csv('messi_goals_caps.csv')
messi_opp = pd.read_csv('messi_opponent_goals.csv')

# Cargar los datos de Ronaldo
ronaldo_comp = pd.read_csv('ronaldo_competition_goals.csv')
ronaldo_year = pd.read_csv('ronaldo_goals_caps.csv')
ronaldo_opp = pd.read_csv('ronaldo_opponent_goals.csv')

# Función para mostrar información básica
def display_basic_info(df, name):
    print(f"\n=== Información básica de {name} ===")
    print(df.head())
    print("\nResumen estadístico:")
    print(df.describe())
    print("\nTipos de datos:")
    print(df.dtypes)

# Mostrar información básica de cada dataset
display_basic_info(messi_comp, "Messi - Competitions")
display_basic_info(messi_year, "Messi - Goles por año")
display_basic_info(messi_opp, "Messi - Goles por oponente")

display_basic_info(ronaldo_comp, "Ronaldo - Competitions")
display_basic_info(ronaldo_year, "Ronaldo - Goles por año")
display_basic_info(ronaldo_opp, "Ronaldo - Goles por oponente")

# Visualización: Goles por año comparativos
plt.figure(figsize=(12, 6))
plt.plot(messi_year['Year'], messi_year['goals'], label='Messi', marker='o')
plt.plot(ronaldo_year['Year'], ronaldo_year['Goals'], label='Ronaldo', marker='o')
plt.title('Goles internacionales por año')
plt.xlabel('Año')
plt.ylabel('Goles')
plt.legend()
plt.grid(True)
plt.show()

# Visualización: Goles por competencia
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

messi_comp_sorted = messi_comp.sort_values('Goals', ascending=False)
axes[0].barh(messi_comp_sorted['Competition'], messi_comp_sorted['Goals'])
axes[0].set_title('Messi - Goles por competencia')
axes[0].set_xlabel('Goles')

ronaldo_comp_sorted = ronaldo_comp.sort_values('Goals', ascending=False)
axes[1].barh(ronaldo_comp_sorted['Competition'], ronaldo_comp_sorted['Goals'])
axes[1].set_title('Ronaldo - Goles por competencia')
axes[1].set_xlabel('Goles')

plt.tight_layout()
plt.show()

# Top 10 oponentes
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

messi_opp_sorted = messi_opp.sort_values('Goals', ascending=False).head(10)
axes[0].barh(messi_opp_sorted['Opponent'], messi_opp_sorted['Goals'])
axes[0].set_title('Messi - Top 10 oponentes')
axes[0].set_xlabel('Goles')

ronaldo_opp_sorted = ronaldo_opp.sort_values('Goals', ascending=False).head(10)
axes[1].barh(ronaldo_opp_sorted['Opponent'], ronaldo_opp_sorted['Goals'])
axes[1].set_title('Ronaldo - Top 10 oponentes')
axes[1].set_xlabel('Goles')

plt.tight_layout()
plt.show()

# Estadísticas resumen
print("\n=== Estadísticas resumen ===")
print(f"Total goles de Messi: {messi_year['goals'].sum()}")
print(f"Total goles de Ronaldo: {ronaldo_year['Goals'].sum()}")
print(f"Promedio de goles por partido de Messi: {messi_year['goals'].sum() / messi_year['caps'].sum():.2f}")
print(f"Promedio de goles por partido de Ronaldo: {ronaldo_year['Goals'].sum() / ronaldo_year['Caps'].sum():.2f}")